#ifndef __errorno_H__
#define __errorno_H__


typedef enum _eCloudAccessErrorCode
{
    ERROR_CODE_SUCCESS,

    ERROR_CODE_LKM_ERROR = 0x50000,
    ERROR_CODE_LKM_W_ERROR,
    ERROR_CODE_LKM_R_ERROR,
    ERROR_CODE_LKM_INPUT_FORMAT,
    ERROR_CODE_LKM_DESTROY,
    ERROR_CODE_LKM_INTERNAL_ERR,
    ERROR_CODE_LKM_INTERNAL_ERR_GET_NODE_LOCK_FAIL,
    ERROR_CODE_LKM_INTERNAL_SEARCH_NOT_FOUND,

    ERROR_CODE_GENERAL_ERROR_START = 0xf0000,
    ERROR_CODE_GENERAL_ERROR,
    ERROR_CODE_NETWORK_ERROR,
    ERROR_CODE_SERVER_RETURN_FORMAT_ERROR,
    ERROR_CODE_NULL_POINT_EXCEPTION,
    ERROR_CODE_NONEXPECT_ERROR,
    ERROR_CODE_READ_BIG_FILE,
    ERROR_CODE_CNT,

}eCloudAccessErrorCode;

#endif

